import { BuildingDefinition } from "./types";

/**
 * Post-apocalyptic building definitions for Wasteland Rebuilders
 * Now using AI-generated wasteland-themed sprites
 */
export const WASTELAND_BUILDINGS: Record<string, BuildingDefinition> = {
  // ===== RESIDENTIAL (Shelter) =====
  "scrap-shack": {
    id: "scrap-shack",
    name: "Scrap Shack",
    category: "residential",
    footprint: { width: 2, height: 2 },
    sprites: {
      south: "/Building/wasteland/2x2scrap_shack_south.png",
      north: "/Building/wasteland/2x2scrap_shack_north.png",
      east: "/Building/wasteland/2x2scrap_shack_east.png",
      west: "/Building/wasteland/2x2scrap_shack_west.png",
    },
    icon: "🏚️",
    supportsRotation: true,
    cost: {
      scrap: 25,
      food: 0,
      water: 0,
      power: 0,
      medicine: 0,
      caps: 0,
    },
    description: "Basic shelter for survivors. Houses 2-3 people.",
  },

  "reinforced-bunker": {
    id: "reinforced-bunker",
    name: "Reinforced Bunker",
    category: "residential",
    footprint: { width: 2, height: 3 },
    footprintByOrientation: {
      south: { width: 2, height: 3 },
      north: { width: 2, height: 3 },
      east: { width: 3, height: 2 },
      west: { width: 3, height: 2 },
    },
    sprites: {
      south: "/Building/residential/2x3brownstone_south.png",
      north: "/Building/residential/2x3brownstone_north.png",
      east: "/Building/residential/3x2brownstone_east.png",
      west: "/Building/residential/3x2brownstone_west.png",
    },
    icon: "🏠",
    supportsRotation: true,
    cost: {
      scrap: 50,
      food: 0,
      water: 0,
      power: 0,
      medicine: 0,
      caps: 0,
    },
    description: "Rad-proof shelter. Houses 5 people safely.",
  },

  "survivor-apartments": {
    id: "survivor-apartments",
    name: "Survivor Apartments",
    category: "residential",
    footprint: { width: 3, height: 3 },
    sprites: {
      south: "/Building/residential/3x380s_small_apartment_building_south.png",
      north: "/Building/residential/3x380s_small_apartment_building_north.png",
      east: "/Building/residential/3x380s_small_apartment_building_east.png",
      west: "/Building/residential/3x380s_small_apartment_building_west.png",
    },
    icon: "🏢",
    supportsRotation: true,
    cost: {
      scrap: 100,
      food: 0,
      water: 0,
      power: 0,
      medicine: 0,
      caps: 50,
    },
    description: "Restored pre-war apartments. Houses 10 people.",
  },

  // ===== RESOURCE PRODUCTION =====
  "scavenging-station": {
    id: "scavenging-station",
    name: "Scavenging Station",
    category: "resource",
    footprint: { width: 2, height: 2 },
    sprites: {
      south: "/Building/wasteland/2x2scrap_shack_south.png",
      north: "/Building/wasteland/2x2scrap_shack_north.png",
      east: "/Building/wasteland/2x2scrap_shack_east.png",
      west: "/Building/wasteland/2x2scrap_shack_west.png",
    },
    icon: "🔨",
    supportsRotation: true,
    cost: {
      scrap: 30,
      food: 0,
      water: 0,
      power: 0,
      medicine: 0,
      caps: 0,
    },
    produces: {
      scrap: 2,
    },
    description: "Salvages materials from ruins. +2 scrap/sec",
  },

  "water-purifier": {
    id: "water-purifier",
    name: "Water Purifier",
    category: "resource",
    footprint: { width: 2, height: 2 },
    sprites: {
      south: "/Building/wasteland/2x2water_purifier_south.png",
      north: "/Building/wasteland/2x2water_purifier_south.png",
      east: "/Building/wasteland/2x2water_purifier_south.png",
      west: "/Building/wasteland/2x2water_purifier_south.png",
    },
    icon: "💧",
    supportsRotation: false,
    cost: {
      scrap: 40,
      food: 0,
      water: 0,
      power: 0,
      medicine: 0,
      caps: 0,
    },
    produces: {
      water: 3,
    },
    consumes: {
      power: 1,
    },
    description: "Purifies contaminated water. +3 water/sec (needs power)",
  },

  "hydroponic-farm": {
    id: "hydroponic-farm",
    name: "Hydroponic Farm",
    category: "resource",
    footprint: { width: 2, height: 2 },
    sprites: {
      south: "/Building/wasteland/2x2hydroponic_farm_south.png",
      north: "/Building/wasteland/2x2hydroponic_farm_south.png",
      east: "/Building/wasteland/2x2hydroponic_farm_south.png",
      west: "/Building/wasteland/2x2hydroponic_farm_south.png",
    },
    icon: "🌱",
    supportsRotation: false,
    cost: {
      scrap: 60,
      food: 0,
      water: 0,
      power: 0,
      medicine: 0,
      caps: 30,
    },
    produces: {
      food: 2,
    },
    consumes: {
      water: 1,
      power: 1,
    },
    description: "Advanced farming. +2 food/sec (needs water + power)",
  },

  // ===== INFRASTRUCTURE =====
  "solar-array": {
    id: "solar-array",
    name: "Solar Array",
    category: "infrastructure",
    footprint: { width: 2, height: 2 },
    sprites: {
      south: "/Building/wasteland/2x2solar_array_south.png",
      north: "/Building/wasteland/2x2solar_array_south.png",
      east: "/Building/wasteland/2x2solar_array_south.png",
      west: "/Building/wasteland/2x2solar_array_south.png",
    },
    icon: "☀️",
    supportsRotation: false,
    cost: {
      scrap: 50,
      food: 0,
      water: 0,
      power: 0,
      medicine: 0,
      caps: 50,
    },
    produces: {
      power: 5,
    },
    description: "Clean energy from the sun. +5 power/sec",
  },

  "generator": {
    id: "generator",
    name: "Scrap Generator",
    category: "infrastructure",
    footprint: { width: 1, height: 1 },
    sprites: {
      south: "/Building/wasteland/1x1generator_south.png",
      north: "/Building/wasteland/1x1generator_south.png",
      east: "/Building/wasteland/1x1generator_south.png",
      west: "/Building/wasteland/1x1generator_south.png",
    },
    icon: "⚡",
    supportsRotation: false,
    cost: {
      scrap: 20,
      food: 0,
      water: 0,
      power: 0,
      medicine: 0,
      caps: 0,
    },
    produces: {
      power: 3,
    },
    consumes: {
      scrap: 0.5,
    },
    description: "Burns scrap for power. +3 power/sec (-0.5 scrap/sec)",
  },

  "med-tent": {
    id: "med-tent",
    name: "Medical Tent",
    category: "infrastructure",
    footprint: { width: 2, height: 2 },
    sprites: {
      south: "/Building/wasteland/2x2med_tent_south.png",
      north: "/Building/wasteland/2x2med_tent_south.png",
      east: "/Building/wasteland/2x2med_tent_south.png",
      west: "/Building/wasteland/2x2med_tent_south.png",
    },
    icon: "🏥",
    supportsRotation: false,
    cost: {
      scrap: 70,
      food: 0,
      water: 0,
      power: 0,
      medicine: 20,
      caps: 40,
    },
    produces: {
      medicine: 1,
    },
    consumes: {
      water: 1,
      power: 1,
    },
    description: "Produces medicine. +1 medicine/sec (needs water + power)",
  },

  "radio-tower": {
    id: "radio-tower",
    name: "Radio Tower",
    category: "infrastructure",
    footprint: { width: 1, height: 2 },
    sprites: {
      south: "/Building/wasteland/1x2radio_tower_south.png",
      north: "/Building/wasteland/1x2radio_tower_south.png",
      east: "/Building/wasteland/1x2radio_tower_south.png",
      west: "/Building/wasteland/1x2radio_tower_south.png",
    },
    icon: "📻",
    supportsRotation: false,
    cost: {
      scrap: 70,
      food: 0,
      water: 0,
      power: 0,
      medicine: 0,
      caps: 60,
    },
    consumes: {
      power: 2,
    },
    description: "Attracts new settlers. (needs power)",
  },

  // ===== DEFENSE =====
  "guard-tower": {
    id: "guard-tower",
    name: "Guard Tower",
    category: "defense",
    footprint: { width: 2, height: 2 },
    sprites: {
      south: "/Building/wasteland/2x2guard_tower_south.png",
      north: "/Building/wasteland/2x2guard_tower_south.png",
      east: "/Building/wasteland/2x2guard_tower_south.png",
      west: "/Building/wasteland/2x2guard_tower_south.png",
    },
    icon: "🗼",
    supportsRotation: false,
    cost: {
      scrap: 60,
      food: 0,
      water: 0,
      power: 0,
      medicine: 0,
      caps: 30,
    },
    description: "Provides defense against raiders. Requires 1 guard.",
  },

  "barricade": {
    id: "barricade",
    name: "Barricade",
    category: "defense",
    footprint: { width: 1, height: 1 },
    sprites: {
      south: "/Props/wasteland/1x1barricade_south.png",
      north: "/Props/wasteland/1x1barricade_south.png",
      east: "/Props/wasteland/1x1barricade_south.png",
      west: "/Props/wasteland/1x1barricade_south.png",
    },
    icon: "🧱",
    supportsRotation: false,
    cost: {
      scrap: 10,
      food: 0,
      water: 0,
      power: 0,
      medicine: 0,
      caps: 0,
    },
    description: "Blocks movement. Basic defense.",
  },

  // ===== COMMERCIAL =====
  "trading-post": {
    id: "trading-post",
    name: "Trading Post",
    category: "commercial",
    footprint: { width: 3, height: 3 },
    sprites: {
      south: "/Building/wasteland/3x3trading_post_south.png",
      north: "/Building/wasteland/3x3trading_post_south.png",
      east: "/Building/wasteland/3x3trading_post_south.png",
      west: "/Building/wasteland/3x3trading_post_south.png",
    },
    icon: "🏪",
    supportsRotation: false,
    cost: {
      scrap: 80,
      food: 0,
      water: 0,
      power: 0,
      medicine: 0,
      caps: 50,
    },
    produces: {
      caps: 2,
    },
    description: "Attracts traders. +2 caps/sec",
  },

  // ===== PROPS/DECORATION =====
  "campfire": {
    id: "campfire",
    name: "Campfire",
    category: "props",
    footprint: { width: 1, height: 1 },
    sprites: {
      south: "/Props/wasteland/1x1campfire_south.png",
      north: "/Props/wasteland/1x1campfire_south.png",
      east: "/Props/wasteland/1x1campfire_south.png",
      west: "/Props/wasteland/1x1campfire_south.png",
    },
    icon: "🔥",
    supportsRotation: false,
    isDecoration: true,
    cost: {
      scrap: 5,
      food: 0,
      water: 0,
      power: 0,
      medicine: 0,
      caps: 0,
    },
    description: "Morale boost. Survivors gather here.",
  },

  "dead-tree": {
    id: "dead-tree",
    name: "Dead Tree",
    category: "props",
    footprint: { width: 1, height: 1 },
    renderSize: { width: 4, height: 4 },
    sprites: {
      south: "/Props/wasteland/1x1dead_tree_south.png",
      north: "/Props/wasteland/1x1dead_tree_south.png",
      east: "/Props/wasteland/1x1dead_tree_south.png",
      west: "/Props/wasteland/1x1dead_tree_south.png",
    },
    icon: "🌳",
    supportsRotation: false,
    isDecoration: true,
    cost: {
      scrap: 0,
      food: 0,
      water: 0,
      power: 0,
      medicine: 0,
      caps: 0,
    },
    description: "Withered tree. Free to place.",
  },

  "car-wreck": {
    id: "car-wreck",
    name: "Rusted Vehicle",
    category: "props",
    footprint: { width: 2, height: 1 },
    sprites: {
      south: "/Props/wasteland/2x1car_wreck_south.png",
      north: "/Props/wasteland/2x1car_wreck_south.png",
      east: "/Props/wasteland/2x1car_wreck_south.png",
      west: "/Props/wasteland/2x1car_wreck_south.png",
    },
    icon: "🚗",
    supportsRotation: false,
    isDecoration: true,
    cost: {
      scrap: 5,
      food: 0,
      water: 0,
      power: 0,
      medicine: 0,
      caps: 0,
    },
    description: "Salvaged wreck. Wasteland atmosphere.",
  },

  "scrap-pile": {
    id: "scrap-pile",
    name: "Scrap Pile",
    category: "props",
    footprint: { width: 1, height: 1 },
    sprites: {
      south: "/Props/wasteland/1x1scrap_pile_south.png",
      north: "/Props/wasteland/1x1scrap_pile_south.png",
      east: "/Props/wasteland/1x1scrap_pile_south.png",
      west: "/Props/wasteland/1x1scrap_pile_south.png",
    },
    icon: "🗑️",
    supportsRotation: false,
    isDecoration: true,
    cost: {
      scrap: 0,
      food: 0,
      water: 0,
      power: 0,
      medicine: 0,
      caps: 0,
    },
    description: "Pile of salvageable junk.",
  },

  "water-barrel": {
    id: "water-barrel",
    name: "Water Barrel",
    category: "props",
    footprint: { width: 1, height: 1 },
    sprites: {
      south: "/Props/wasteland/1x1water_barrel_south.png",
      north: "/Props/wasteland/1x1water_barrel_south.png",
      east: "/Props/wasteland/1x1water_barrel_south.png",
      west: "/Props/wasteland/1x1water_barrel_south.png",
    },
    icon: "🛢️",
    supportsRotation: false,
    isDecoration: true,
    cost: {
      scrap: 10,
      food: 0,
      water: 0,
      power: 0,
      medicine: 0,
      caps: 0,
    },
    storage: {
      water: 50,
    },
    description: "Stores extra water. +50 water capacity.",
  },

  "skull-pile": {
    id: "skull-pile",
    name: "Skull Pile",
    category: "props",
    footprint: { width: 1, height: 1 },
    sprites: {
      south: "/Props/wasteland/1x1skull_pile_south.png",
      north: "/Props/wasteland/1x1skull_pile_south.png",
      east: "/Props/wasteland/1x1skull_pile_south.png",
      west: "/Props/wasteland/1x1skull_pile_south.png",
    },
    icon: "💀",
    supportsRotation: false,
    isDecoration: true,
    cost: {
      scrap: 0,
      food: 0,
      water: 0,
      power: 0,
      medicine: 0,
      caps: 0,
    },
    description: "A grim reminder of the old world.",
  },
};
